---
- src: geerlingguy.composer
  version: 1.6.1
- src: geerlingguy.mysql
  version: 2.8.0
- src: geerlingguy.php
  version: 3.5.0
- src: geerlingguy.php-mysql
  version: 2.0.1
- src: geerlingguy.php-versions
  version: 2.0.0
- src: geerlingguy.php-xdebug
  version: 2.4.0
